name: Hello World2
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
          echo "this is line 1"
          echo "this is line 2"
          echo "this is line 3"
