name: Hello World
on: workflow_dispatch
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A build demo"
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Test phase
        run: echo "A test Demo"
  deploy :
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "A deploy demo"
        
